package item;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLConnection;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.widget.ImageView;
import android.widget.RatingBar;

public class Item implements Serializable  {		
		/**
		 * Generated by Eclipse
		 */
		private static final long serialVersionUID = 5527258407135652423L;

		private Bitmap item_image;
		private String name;
		private String address;
		private Bitmap rating_image;
		private Bitmap facebook_image;
		private int facebook_likes;
		
		public Item(String ItemUrl,String ItemName, String Address, String RatingUrl, String FBUrl, int FBlikes) {
			this.setItem_image(ItemUrl);
			this.setName(ItemName);
			this.setAddress(Address);
			this.setRating_image(RatingUrl);
			this.setFacebook_image(FBUrl);
			this.setFacebook_likes(FBlikes);
		}

		public void setName(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}

		public String getAddress() {
			return address;
		}

		public void setAddress(String address) {
			this.address = address;
		}

		public int getFacebook_likes() {
			return facebook_likes;
		}

		public void setFacebook_likes(int facebook_likes) {
			this.facebook_likes = facebook_likes;
		}

		public Bitmap getFacebook_image() {
			return facebook_image;
		}

		public void setFacebook_image(String url) {
			BitmapFactory.Options bitmapoptions;
			bitmapoptions = new BitmapFactory.Options();
			bitmapoptions.inSampleSize = 1;
		    InputStream in = null;       
		       try {
		           in = OpenHttpConnection(url);
		           this.facebook_image = BitmapFactory.decodeStream(in, null, bitmapoptions);
		           in.close();
		       } catch (IOException e1) {
		       }          
		}

		public Bitmap getItem_image() {
			return item_image;
		}

		public void setItem_image(String url) {
			BitmapFactory.Options bitmapoptions;
			bitmapoptions = new BitmapFactory.Options();
			bitmapoptions.inSampleSize = 1;
		    InputStream in = null;       
		       try {
		           in = OpenHttpConnection(url);
		           this.item_image = BitmapFactory.decodeStream(in, null, bitmapoptions);
		           in.close();
		       } catch (IOException e1) {
		       }    
		}

		public Bitmap getRating_image() {
			return rating_image;
		}

		public void setRating_image(String url) {
			BitmapFactory.Options bitmapoptions;
			bitmapoptions = new BitmapFactory.Options();
			bitmapoptions.inSampleSize = 1;
		    InputStream in = null;       
		       try {
		           in = OpenHttpConnection(url);
		           this.rating_image = BitmapFactory.decodeStream(in, null, bitmapoptions);
		           in.close();
		       } catch (IOException e1) {
		       }    
		}
		
		/*Used to setup connection with URl used to set up the images*/ 
		private InputStream OpenHttpConnection(String strURL) throws IOException{
			 InputStream inputStream = null;
			 URL url = new URL(strURL);
			 URLConnection conn = url.openConnection();
			 try{
				  HttpURLConnection httpConn = (HttpURLConnection)conn;
				  httpConn.setRequestMethod("GET");
				  httpConn.connect();
				  if (httpConn.getResponseCode() == HttpURLConnection.HTTP_OK) {
					  inputStream = httpConn.getInputStream();
				  }
			 }catch (Exception ex)
			 {
			 }
			 return inputStream;
		}
}
